DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS USER (
  EMAIL VARCHAR(255) PRIMARY KEY,
  PASSWORD VARCHAR(36),
  VERSION INTEGER
);

INSERT INTO USER VALUES('user@localhost', 'password', 0);
